name: Docker Test
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . -f Dockerfile -t ${{ env.IMAGE_NAME }}

      - name: Run all tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace --workdir /workspace --env CI=true ${{ env.IMAGE_NAME }} test
